### PR TITLE
feat: real image dataset support

### PR DESCRIPTION
**Pull request by jacobowitz**
This PR adds two things:

1. Support for reading image based datasets
2. A text based flow example using Amazon reviews (taken from https://www.kaggle.com/bittlingmayer/amazonreviews). The dataset contains 3 million documents, in this example I am splitting it word by word (mainly to generate a lot of documents) and one can search for words then. This yields an example where we could index/query hundreds of millions of documents.

The dataset is downloaded from S3 automatically if AWS credentials are set. We probably need to extend this example to run in a distributed fashion on AWS and change the settings (like execution time etc) accordingly. I guess its performance is mainly driven by encoding performance though.
We may also want to replace the NumpyIndexer with a Faiss Indexer?

### CODE REVIEW

**Comment by jacobowitz** [comment]
Actually for the text based datasets the formats will change all the time, so we probably cant have a unified method to access the datasets (second question above), but we need specific methods for specific datasets

**Comment by deepankarm** [comment]
> I am not closing the ScandirIterator as it is hard to say when we are done processing the dataset? I guess it should be okay here, but its not really clean.

Should be okay for now.

**Comment by jacobowitz** [comment]
rebased, @deepankarm  can you have a look at this one please? It basically just adds the possibility to add image based dataset and use another text based dataset which is based on amazon reviews.

**Comment by deepankarm** [comment]
The PR looks nice! Let's test it today on end-to-end remote with terraform

**Review by deepankarm — APPROVED** [review]

**Pull request merged**
